# Generated by Django 4.1.7 on 2023-11-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_vencimiento',
        ),
    ]
