# Generated by Django 5.0.4 on 2024-04-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tarea_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='materia',
            field=models.CharField(default='', max_length=100),
        ),
    ]
